server:
  port: 9000

spring:
  application:
    name: auth-service
  spring:
  cloud:
    gateway:
      routes:
        - id: milk-shop-service
          uri: lb://MILK-SHOP-SERVICE
          predicates:
            - Path=/api/v1/milk-shop/**
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/coop_db?currentSchema=schema_admin
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      # Defaults to localhost for local dev. Docker Compose will inject EUREKA_HOST=discovery-server.
      defaultZone: http://discovery-server:8761/eureka/