
services:
  postgres-db:
    image: postgres:16-alpine
    container_name: coop_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: coop_db
    ports:
      - "5433:5432" 
    volumes:
      - ./coop.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - coop-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: coop_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@coop.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80" # Access pgAdmin via localhost:5050
    depends_on:
      - postgres-db
    networks:
      - coop-network

networks:
  coop-network:
    driver: bridge