server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      # Update to the new 'server.webflux' structure
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://localhost:9000
              predicates:
                - Path=/auth/**
              filters:
                - AuthenticationFilter

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false