server:
  port: 9003

spring:
  application:
    name: room-section-service
  datasource:
    # Bulletproof config: Defaults to localhost:5433 for local IDE development.
    # Docker Compose will override these with DB_HOST=postgres-db and DB_PORT=5432.
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/coop_db?currentSchema=schema_room_section
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: schema_room_section

# Added Eureka configuration so it can join the network
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
