spring.application.name=milk-shop-service
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5433/coop_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=schema_milk_shopspring.application.name=milk-shop-service
